version: "2"
services:
  nzbtoproxy:
    build: ./docker/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
    networks:
      - nzbproxy

  torproxy:
    image: peterdavehello/tor-socks-proxy
    ports:
      - "9150:9150"
    networks:
      - nzbproxy
    depends_on:
      - nzbtoproxy

networks:
  nzbproxy:
    driver: bridge
